name: order_app
description: order app

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  shared_preferences: ^0.5.1+1
  fluttertoast: ^3.0.1
  json_annotation: ^2.4.0
  flutter_redux: ^0.5.3
  device_info: ^0.4.0+1
  connectivity: ^0.4.3+1
  url_launcher: ^5.0.2
  flutter_statusbar: ^0.0.1
  dio: ^2.1.4
  event_bus:  ^1.1.0
  flutter_cache_manager: ^0.3.2
  cached_network_image: ^0.8.0
  permission_handler: 3.0.2
  rxdart: ^0.22.0
  android_intent: ^0.3.0
  webview_flutter: ^0.3.7+1
  flutter_localizations:
    sdk: flutter
  photo_view:
    git:
      url: https://github.com/CarSmallGuo/photo_view.git
      ref: 1fc0effdb8269f4f6bb61186acb127890002b770

dev_dependencies:
  build_runner: ^1.2.8
  json_serializable: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
#存放资源
  assets:
  - static/images/bg_logo.jpg
  - static/images/icon_decrease.png
  - static/images/icon_plus.png
